In [1]:
import numpy as np
import tensorflow as tf

In [15]:
# f: R^d -> R^c
def get_data(m, d, c):
    X = np.random.uniform(-1, +1, (m, d))
    A = np.random.uniform(-1, +1, (d, c))
    E = np.random.normal (0, 0.1, (m, c))
    Y = X.dot(A)+E
    
    return X, Y, A

In [16]:
X, Y, A = get_data(1000, 4, 2)
print(X.shape, Y.shape, A.shape)

((1000, 4), (1000, 2), (4, 2))


In [17]:
print(A)

[[-0.50252473 -0.56376033]
 [-0.68566976 -0.28328791]
 [ 0.3926062  -0.31462611]
 [ 0.52617721 -0.04179404]]


In [24]:
X_tf = tf.constant(X, dtype=tf.float32)
Y_tf = tf.constant(Y, dtype=tf.float32)
A_tf = tf.Variable(np.zeros(A.shape), dtype=tf.float32)
F_tf = tf.matmul(X_tf, A_tf)

loss_tf = tf.reduce_mean(tf.square(F_tf-Y_tf))
step_tf = tf.train.GradientDescentOptimizer(1E-3).minimize(loss_tf)

with tf.Session() as sess:
    
    sess.run(tf.global_variables_initializer())
    
    num_iterations, print_every = 2**14, 2**10
    for i in range(num_iterations):
        
        sess.run(step_tf)
        
        if i % print_every == print_every-1:
            print(sess.run(loss_tf))
    
        
    A_opt = sess.run(A_tf)


0.14695819
0.08025954
0.04616877
0.028724503
0.019788047
0.0152047165
0.0128513
0.011641508
0.011018888
0.010698099
0.010532631
0.010447183
0.010403008
0.010380148
0.010368305
0.010362163


In [27]:
print(A)
print("")
print(A_opt)

[[-0.50252473 -0.56376033]
 [-0.68566976 -0.28328791]
 [ 0.3926062  -0.31462611]
 [ 0.52617721 -0.04179404]]

[[-0.49429384 -0.56082743]
 [-0.67869043 -0.28039393]
 [ 0.38294655 -0.30882356]
 [ 0.52574795 -0.04175581]]
